import com.mathworks.toolbox.javabuilder.*;
import mapGeneration.Map;

/**
 *
 * Sample driver code that is integrated with a compiled MATLAB function
 * generated by MATLAB Compiler SDK.
 *
 * Refer to the MATLAB Compiler SDK documentation for more
 * information.
 *
 * @see com.mathworks.toolbox.javabuilder.MWArray
 *
 */
public class mapGenerationSample1 {

	private static Map mapInstance;

	private static void setup() throws MWException {
		mapInstance = new Map();
	}

	/**
	 * Sample code for {@link Map#mapGeneration(int, Object...)}.
	 */
	public static void mapGenerationExample() {
		MWArray obsIn = null;
		MWArray dimIn = null;
		MWNumericArray gidOut = null;
		MWNumericArray shapeposOut = null;
		Object[] results = null;
		try {
			double[][] obsInData = {{250.0, 480.0, 340.0}, {60.0, 250.0, 60.0}};
			obsIn = new MWNumericArray(obsInData, MWClassID.DOUBLE);
			double[] dimInData = {1024.0, 1024.0};
			dimIn = new MWNumericArray(dimInData, MWClassID.DOUBLE);
			results = mapInstance.mapGeneration(2, obsIn, dimIn);
			if (results[0] instanceof MWNumericArray) {
				gidOut = (MWNumericArray) results[0];
			}
			if (results[1] instanceof MWNumericArray) {
				shapeposOut = (MWNumericArray) results[1];
			}
			System.out.println(gidOut);
			System.out.println(shapeposOut);
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			// Dispose of native resources
			MWArray.disposeArray(obsIn);
			MWArray.disposeArray(dimIn);
			MWArray.disposeArray(results);
		}
	}

	public static void main(String[] args) {
		try {
			setup();
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
		try {
			mapGenerationExample();
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		} finally {
			// Dispose of native resources
			mapInstance.dispose();
		}
	}

}
