import com.mathworks.toolbox.javabuilder.*;
import MatlabUtility.MatlabUtility;

/**
 *
 * Sample driver code that is integrated with a compiled MATLAB function
 * generated by MATLAB Compiler SDK.
 *
 * Refer to the MATLAB Compiler SDK documentation for more
 * information.
 *
 * @see com.mathworks.toolbox.javabuilder.MWArray
 *
 */
public class visioneSample2 {

	private static MatlabUtility matlabutilityInstance;

	private static void setup() throws MWException {
		matlabutilityInstance = new MatlabUtility();
	}

	/**
	 * Sample code for {@link MatlabUtility#visione(int, Object...)}.
	 */
	public static void visioneExample() {
		MWArray filenameIn = null;
		MWNumericArray objAreaOut = null;
		MWNumericArray objPerimOut = null;
		MWNumericArray objShapeOut = null;
		MWNumericArray angOut = null;
		Object[] results = null;
		try {
			String filenameInData = ".\\mapgenerationimg\\visione\\sfera.jpg";
			filenameIn = new MWCharArray(filenameInData);
			results = matlabutilityInstance.visione(4, filenameIn);
			if (results[0] instanceof MWNumericArray) {
				objAreaOut = (MWNumericArray) results[0];
			}
			if (results[1] instanceof MWNumericArray) {
				objPerimOut = (MWNumericArray) results[1];
			}
			if (results[2] instanceof MWNumericArray) {
				objShapeOut = (MWNumericArray) results[2];
			}
			if (results[3] instanceof MWNumericArray) {
				angOut = (MWNumericArray) results[3];
			}
			System.out.println(objAreaOut);
			System.out.println(objPerimOut);
			System.out.println(objShapeOut);
			System.out.println(angOut);
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			// Dispose of native resources
			MWArray.disposeArray(filenameIn);
			MWArray.disposeArray(results);
		}
	}

	public static void main(String[] args) {
		try {
			setup();
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
		try {
			visioneExample();
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		} finally {
			// Dispose of native resources
			matlabutilityInstance.dispose();
		}
	}

}
